apiVersion: v1
kind: Secret
metadata:
  name: elm-certificate-store
type: Opaque
data:
  username: {{ "user" | b64enc | quote }}
  password: {{ randAlphaNum 10 | b64enc | quote }}
type: kubernetes.io/basic-auth