apiVersion: v1
kind: Service
metadata:
  name: elm-app-service
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: 'elm-app-service'
spec:
  selector: 
    app: elm-app
  type: ClusterIP  
  ports:
    - port: 9443
      targetPort: 9443